name: Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v3
    - name: Build
      run: docker build -t helloworld .
    - name : Run
      run : docker run --rm -ti --name helloworlnew helloworld
